name: cloudinary_sdk
description: This is a dart package for Cloudinary API that allows you to upload and manage files in your cloudinary cloud.
version: 4.0.0+8
homepage: https://github.com/luis901101/cloudinary-sdk

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  crypto: ^3.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1